### ISSUE TITLE
Faraway 2015 Chapter 2

### ISSUE THREAD

**Issue by hmcmonagle** [QERM514/assistance#12]
Hi Mark,

In the section of Chapter 2 (shown below), I don't understand why it's possible to multiply the vector beta, which looks like it'll be a 4x1 matrix, times the matrix X, which has n number of rows and 4 columns. Wouldn't this mean the inside terms are not the same (4x1 matrix) * (nx4 matrix) unless by coincidence the number of observations n equals 4?

Thanks in advance!

Faraday 2015 Chapter 2 p. 14:

<img width="826" alt="Screen Shot 2020-04-10 at 9 53 03 AM" src="https://user-images.githubusercontent.com/43573863/78996201-1b8bdc80-7b12-11ea-88ce-ee5613c61c7d.png">

**Comment by mdscheuerell** [comment]
Hi Helena. It looks like you've confused yourself with the order of operations. As you indicated, beta is [4 x 1] and X is [n x 4], so indeed it won't work to multiply `beta %*% X`. However, look at the equation for y again. It says to instead multiply `X %*% beta`, which will work.

You might want to check out slides 21-24 from [Wed's lecture](https://qerm514.github.io/website/lectures/week_02/lec_05_intro_to_linear_models.html#21).

**Comment by hmcmonagle** [comment]
Oops, that was a careless mistake not to notice the order of operations there. The lecture slides confirmed how those matrices should look when multiplying them together. Thanks!
