### ISSUE TITLE
HW 3 Questions

### ISSUE THREAD

**Issue by abigailkeller** [QERM514/assistance#16]
I'm working on the student t test for the residuals, and I'm a little confused about the degrees of freedom. I would assume that it would be n - k - 1. The code from lab looks like (with "full_model" replacing the model in your example):

 df <- length(full_model) - length(coef(full_model)) - 1

I'm confused about the length(full_model) part because it is not equal to n and instead is equal to the elements (coefficients, residuals, effects, etc) of the model.

Should it be equal to n? (38)

**Comment by mdscheuerell** [comment]
Good catch, @abigailkeller!

You are indeed correct that for the studentized residuals, the statistic is distributed as a *t*-distribution with

*df* = *n - k* - 1

The example in lab was based upon the `m1` model estimated [here](https://qerm514.github.io/website/labs/week_03/diagnostics_and_errors.html#unusual_observations). It turns out that

`length(m1) == 12`,

but I made a mistake and instead n = 11. I have fixed that section of code to be

```
## get sample size
n_m1 <- nrow(model.matrix(m1))
## get studentized e
t_stud <- rstudent(m1)
## Bonferroni alpha
alpha <- 0.05 / n_m1
## critical t value
df <- n_m1 - length(coef(m1)) - 1 
t_crit <- qt(1 - alpha, df)
## compare t_stud to t_crit
t_stud > t_crit
```

**Comment by abigailkeller** [comment]
Thanks!

**Comment by abigailkeller** [comment]
Also I have two data points where the residuals are very small (one is zero, one is on the scale of 1e-15). When I calculate the Cooks distance and studentized e, it seems like they get thrown out somehow, and I end up with NaN for Cooks d and studentized e. Is this what you would expect to happen?

**Comment by mdscheuerell** [comment]
We talked about this a bit in lab on 4/17. Both of the statistics you're trying to calculate involve a leverage term in the denominator. What are the leverages for those points where you get `NaN`?

In the bigger picture, what does it mean in terms of the leverage when a residual equals 0?

**Comment by abigailkeller** [comment]
Right-- these points have high leverage (equal to 1) and therefore produce a 0 in the denominator for these two statistics. When the residual equals 0, the model is over-compensating for the high leverage points and fitting them exactly. So do we just then assume that they have a large studentized e and Cook's Distance because they are basically infinite?

**Comment by mdscheuerell** [comment]
Yes, the studentized residual and Cook's D is basically infinite because those points have maximum leverage (ie, the fitted values are precisely equal to the data). This is not a desirable feature in the data, but a situation that does arise in unbalanced ANOVA designs like this.
