### ISSUE TITLE
"covariates"

### ISSUE THREAD

**Issue by mjzahn** [QERM514/assistance#29]
I have a terminology question: I've heard and read the term "covariates" used synonymously with predictors and am curious why this is used? I would think covariates would refer to only predictors that covary but it seems like it is used more generally to refer to any independent variable? It is possible that I may be misreading/hearing the use of this term!

**Comment by abigailkeller** [comment]
I have always had the same question, thanks Marie for asking!

**Comment by ameliaduvall** [comment]
Excellent question!

**Comment by mdscheuerell** [comment]
That's a good Q, @mjzahn. I (and many others) tend to use "covariate" in lieu of "predictor", but I'm trying to use the latter more in this course to better align with the language in the textbooks. You are indeed correct that covariate implies covariance, and that's precisely the rationale for referring to the predictors as covariates—with any luck (skill) the response (ie, the "variate") will covary with the predictor.

**Comment by mjzahn** [comment]
Ahh of course! covariate is referring to the response variable not the other predictors. Thank you!
