### ISSUE TITLE
Checking for correlations with categorical predictors

### ISSUE THREAD

**Issue by ameliaduvall** [QERM514/assistance#34]
For homework 5, part d, I tried to check for correlations between the 4 predictors before creating a set of models with all the possible combinations of predictors. However, I received an error message when I tried to include slope aspect: Error in cor(soil[, 2:5]) : 'x' must be numeric. Does anyone know if there a way to check for correlations between predictors if using a categorical predictor?

**Comment by mdscheuerell** [comment]
You could always re-code a categorial variable as "0/1" or "0/1/2/.../n" and then examine the correlation, but I'd encourage you to think about if/how you would actually estimate a parametric measure of association like Pearson's correlation between 2 variables if one of them only has 2 values.
