### ISSUE TITLE
Anyone familiar with Dplyr / Tidyr / Readr 

### ISSUE THREAD

**Issue by RobTour** [QERM514/assistance#37]
Hello all - I am an R novice and have been trying to transform a dataset and run into a wall.
Wondering if anyone with more R experience than me can point me in the right direction. 

This is a data set that I found on the Audubon Society page of annual bird counts (which is interesting but not relevant to this problem) and it is a large csv file from which I only want to pull a subset of the data.  

All I am trying to do is slice out a few rows of data, and then select and rename a few of the columns to create a small table.  

1. I loaded the various libraries
2. I loaded the data set into R Studio, and converted it with tbl_df()
4. Then ran this script:
  crca_annual <-
    cr_cacao %>%
    slice(15:23) %>%
    select(2:5) %>%
    print
(Note: This is not the full script, but the relevant part) 

The table printed as I expected (9 rows x 4 col).  However, I noticed that the data in the columns are stored as factors.  If I look at one of the columns, e.g. crca_annual$X it returns the data shown in the table for that column, but then also shows Levels followed by all the data in that column below my splice.  Hope I am explaining this clearly, trying to be concise.  

I have attached a screenshot of the output in the console.  Robt

![Annotation 2020-05-09 132347](https://user-images.githubusercontent.com/45545625/81484165-73446300-91f8-11ea-8238-53db3e928782.jpg)

**Comment by mdscheuerell** [comment]
> 1. I loaded the various libraries

I'm guessing your fields were converted to strings on the initial import. Did you use `read.csv()` or `readr::read_csv()`? The former has `strings.as.factors = TRUE` by default.

**Comment by RobTour** [comment]
Yes - that did it!  Thank you, Mark
