### ISSUE TITLE
LRTs for multiple REs: convergence issues

### ISSUE THREAD

**Issue by kpjohnson** [QERM514/assistance#42]
I have tried two seeds (514 and 666 [Andre's favorite]) and I get either 5 or 6 simulations with instances of failed model convergence.

Would you advise re-simulating the data for instances like this? Some pseudo-code:

for 1 in 1000 simulations
- simulate data
- fit NULL model
- fit ALT model

- if (summary(ALT model)$fitMsgs has angry text) then simulate data for this simulation # again
- fit NULL model
- fit ALT model
- repeat until no angry text

Thanks in advance!

**Comment by mdscheuerell** [comment]
Interesting. I did not use a bootstrap approach for this problem, but yes, it would seem you could try yet again another seed or just tossing those few draw.
