### ISSUE TITLE
LaTeX compilation error

### ISSUE THREAD

**Issue by ameliaduvall** [QERM514/assistance#43]
Hi all, I made the apparently terrible decision to update R to v4.0 and now I am receiving LaTeX compilation errors when I try to knit Rmarkdown files (+ a pop-up box about luatex.dll not being found). I was able to fix this error a few months ago when I first started using Rmarkdown by downloading Miktex and reinstalling tinytex but it's not working this time. I would be very grateful for any advice or suggestions. Thanks!

**Comment by kpjohnson** [comment]
https://community.rstudio.com/t/knit-to-pdf-not-working-r-v4-0-0-rstudio-v1-2-5042/65776/8

A comment from the creator of tinyteX found in that link:

![image](https://user-images.githubusercontent.com/23057716/81994052-e0426900-95fb-11ea-8b49-a2dd5ee32412.png)

**Comment by mdscheuerell** [comment]
I'm sorry to hear that, @ameliaduvall, but it sounds like the problem may not be on your end based on @kpjohnson's find.

**Comment by ameliaduvall** [comment]
Oh wow, thanks so much @kpjohnson. It's a bittersweet victory when you realize it's not your fault (but it's also out of your hands). 

Thanks for the commiseration too, @mdscheuerell!

**Comment by mdscheuerell** [comment]
> A comment from the creator of tinyteX found in that link

FYI, @kpjohnson and others checking this issue, (if you didn't already know) [Yihui Xie](https://yihui.org/en/about/) is a magical person who has created *many* packages that make our lives easier. If you ever bump into him, buy him a coffee/beer/snack and I'll happily reimburse you.
