### ISSUE TITLE
alpha as slope, or intercept?

### ISSUE THREAD

**Issue by hmcmonagle** [QERM514/assistance#44]
Hi all, 

At the end of class on Wednesday, we talked about how adding delta_i (the random effect of population) to alpha means that you can have a slightly different _slope_ for population (i.e. you can adjust the slope to be greater or less than alpha by delta_i for each population). However, in the typical y = alpha + beta * X + epsilon equation we're used to for a basic linear model, alpha is the _intercept_, not the slope. I understand that, in the deterministic form of the Ricker model (R=alpha * Spawners * exp(−beta * Spawners)exp(ϵ)), where recruits are alone on one side of the equation, alpha (or I guess it's called "a" there) is the slope at the origin. But I'm a little confused about why exactly when we convert to the log(Recruits / Spawners) = α − β * spawners + ϵ form of the Ricker model to make the equation linear, alpha then refers to the intercept and not the slope of the line. Then, in the explanation after class, it sounded like we were saying delta is affecting the "slope of alpha" and that threw me off (because I thought alpha was the intercept). 

If we were to visualize the new, linear model, wouldn't alpha be the _intercept_ that is central to all the deviations from the central tendency by population, not the slope of that linear model? I would have thought β would be the slope in that equation.

If I'm on the right track, does anyone have a good way of explaining why "a" represents _slope_ near the origin in the traditional form of the Ricker model (the first form given above), but "alpha" represents _intercept_ in the linear form of the Ricker model?

Thanks!

**Comment by mdscheuerell** [comment]
Thanks, @hmcmonagle, for trying to clarify this. I totally mangled that discussion.

> If I'm on the right track, does anyone have a good way of explaining why "a" represents slope near the origin in the traditional form of the Ricker model (the first form given above), but "alpha" represents intercept in the linear form of the Ricker model?

The answer boils down to the relationship between the nonlinear form of the Ricker model and the log-linear form that's the focus of the HW. My translation from Kristin's Q to the parameters in the actual model made an implicit connection between the log-link between the two. That is, in the log-linear form described in the HW, the intercept alpha is the log of the slope of the relationship between S_{i,t} and R_{i,t}.

I apologize. This would be so much easier in person with a whiteboard...

**Comment by hmcmonagle** [comment]
No problem at all, thanks for clarifying!! If moving between the nonlinear to the log-linear form was more familiar to me, that implicit connection would have been obvious I think. Ah yes, these days I'm appreciating the value of whiteboards and being able to draw things out too because that often helps, but I know that's harder now. Thanks!

**Comment by kpjohnson** [comment]
This is an awesome question and answer. Helena, I just wanted to stand with in solidarity because I have to reteach myself what alpha and beta (and thus a and b are) every year. I always have to sketch it out something like this:

- alpha is the log(a)  (linearized now, and an intercept)
- a is exp(r) (still slope)
- r is the intrinsic population growth rate (a slope, like Mark said)
- beta is b 
- b is r/k
- k is the population carrying capacity

If you like tying Greek letters to "real life" biological stuff, this is how I visualize this form of the Ricker model. Think about r and K. b is my least favorite to think about because it's a rate divided by numbers--but at the end of the day that ends up being a rate itself.

**Comment by mdscheuerell** [comment]
Thanks, @kpjohnson, this is a nice summary. I'm also going to leave these 2 figures here, which I made for a paper coming out this fall.

![Screen Shot 2020-05-15 at 11 27 57 AM](https://user-images.githubusercontent.com/5048528/82083889-42a07580-969f-11ea-9017-439ed1dae620.png)
