### ISSUE TITLE
HW 6 questions

### ISSUE THREAD

**Issue by mjzahn** [QERM514/assistance#45]
I have two clarifying questions for this week's HW:

1) For the simple fixed effects model in (b) I chose to not include the intercept (meaning I have a -1 in the lm() function) because it makes sense to constrain the line's intercept at the origin given the data. If we did include the intercept, the model could predict negative recruits with a low number of spawners or it could predict positive number of recruits with zero spawners. Both of these cases don't make sense. Is my reasoning on the right track for this or am I off in how I'm making the choice to include/not include the intercept?

2) I'm trying to calculate `delta` only for part (c) and (e) and `eta` in part (d) but can't seem to coerce `coef(model.output)` into a matrix or data.frame in order to subtract the random effects term. I tried this:
`## delta_i only
ranef(mix.mod1)$pop`
`## alpha only
coef(mix.mod1) - ranef(mix.mod1)$pop`
which gives me the difference for the `(Intercept)` column but also subtracts the `spawners` column. Is there a better way to work with the coef() and ranef() outputs to calculate `delta` and `eta`?

Thanks!

**Comment by kpjohnson** [comment]
Hi Marie,

I want to answer the part of your questions about the structure of the coef(mix.mod1) output. Try:

`is.list(coef(mix.mod1))`
`names(coef(mix.mod1)`
`coef(mix.mod1)$pop`
`coef(mix.mod1)$pop[,1]`

**Comment by mjzahn** [comment]
Thank you Kristin! I was trying `coef(mix.mod1)[,1]` to no avail but using `coef(mix.mod1)$pop[,1]` worked!
