### ISSUE TITLE
Autocorrelation for mixed models

### ISSUE THREAD

**Issue by mjzahn** [QERM514/assistance#46]
When working on model diagnostics, I used code from the autocorrelation section [here](https://qerm514.github.io/website/labs/week_06/mixed_models.html), most of which is copied below, and I found that there were some observations that were correlated. I then tried to increase the significance level to 0.1 for funsies but got a higher number of correlations which confused me. When I decreased the alpha critical value to 0.01, I got 0. This is backwards from what I'd expect where a more conservative significance level would yield a conclusion of more correlations, not less. Is there another way to think about this? My brain is also pretty fried at this point so I may be missing something obvious!

``` r 
#### test for autocorrelation
## Type-I error
alpha_crit <- 0.05

## threshold value for rho (correlation)
(rho_crit <- qnorm(1 - alpha_crit/2) / sqrt(20))

## rearrange residuals into matrix; 20 years and 21 populations
resids <- matrix(residuals(mix.mod4), 20, 21)

## get ACF
# only examine correlations out to a lag of 5 years
ACF <- apply(resids, 2, acf, lag.max = 5, plot = FALSE)
ACF <- lapply(ACF, function(x) x$acf)
## convert list to matrix; don't need row 1 b/c rho_0 = 1
ACF <- do.call(cbind, ACF)[-1,]

## check if any |values| > rho_crit
any(abs(ACF) > rho_crit)
# TRUE - there is some autocorrelation

## see which ones/how many
which(abs(ACF) > rho_crit)
length(which(abs(ACF) > rho_crit))
```

**Comment by mdscheuerell** [comment]
This is certainly unintuitive @mjzahn. Perhaps it's easier to think about with respect to the confidence interval you're creating around the rho = 0 line. In your first case where `alpha_crit <- 0.05`, that interval is

`c(-1,1) * qnorm(1 - 0.05/2) / sqrt(20) == c(-0.4382613,  0.4382613)`

In the case where `alpha_crit <- 0.1`, the interval is

`c(-1,1) * qnorm(1 - 0.1/2) / sqrt(20) == c(-0.3678005,  0.3678005)`

So, indeed, the interval with the larger `alpha_crit` is narrower. Why? Well, in the first case we want our interval to have a 95% chance of containing the true value, so it should be necessarily wider than an interval that we hope to have a 90% chance of containing the true value. Both of those would be much wider than an 80% interval:

`c(-1,1) * qnorm(1 - 0.2/2) / sqrt(20) == c(-0.2865636,  0.2865636)`

**Comment by mjzahn** [comment]
Wow that pinched my brain to understand that! Thank you for explaining it in terms of confidence intervals - that makes a lot more sense now!
