### ISSUE TITLE
Model comparison (homework 6 part f)

### ISSUE THREAD

**Issue by hmcmonagle** [QERM514/assistance#47]
Hi all, 

Hope you're all having a good Sunday, and I don't expect any responses over the weekend. It would be great to understand this even after homework is due. 

In part f, we're asked to test whether or not there is data support for including a random effect on the intercept or on the slope, "based on the 3 models you fit in parts c-e." (Notation: I'll call those model c, model, d, model e, etc. here).

I would have thought that the null model would be the simple, stripped down model b, which has no random effects. If so, to test whether there's support to include a random effect for population-level intercepts, I thought we could use anova(reduced model, full model) as we did in the [lab](https://qerm514.github.io/website/labs/week_06/mixed_models.html#model_comparison) to compare the null model (model b) with the model with a random effect on intercept (model c). Seems we'd test for support in the data to include a random effect for population-level slopes by using this same anova() but comparing the model b with model d. 

If I'm on the right track here, how does model e come into play? The question says "based on models c-e), but my comparisons here are based on models b-d with no mention of model e. If the question had asked about whether it makes sense to include random effects on **both** intercept and slope simultaneously, as opposed to random effects on **only** intercept or **only** slope, then I could see how we might answer this question based on models c-e instead of b-d.

I assume I'm missing something here in how we should use e), but wanted to ask first whether I'm mis-interpreting what the question is asking. 

I also assume using anova(reduced model, full model) is more what this questions is asking about, since it mentions a null model, as opposed to comparing AIC values, which is also mentioned in that lab section on [model comparison](https://qerm514.github.io/website/labs/week_06/mixed_models.html#model_comparison). 

Mark, I appreciate your suggestion in your last email to take a look at homework 7 early on to make sure we understand all the questions. Had I done that here I could have asked much earlier!

**Comment by mdscheuerell** [comment]
Good morning, @hmcmonagle. Perhaps take a look at [this section from lab](https://qerm514.github.io/website/labs/week_06/mixed_models.html#single_random_effect) and see if that helps?

> Mark, I appreciate your suggestion in your last email to take a look at homework 7 early on to make sure we understand all the questions.

You're welcome.

**Comment by hmcmonagle** [comment]
Ohh. Got it. Thank you!
