### ISSUE TITLE
HW 7 Data and SARS proportion

### ISSUE THREAD

**Issue by mjzahn** [QERM514/assistance#48]
This may be obvious for some, but I want to clarify whether the `day` column in our HW 7 data is in reference to detections of *both* smolts and adults at BON on the same day? Is SAR (proportion of smolts: adults recorded at the same time) used as a metric of survivorship, despite cohorts varying year-to-year which would change the proportion of smolts:adults surviving from that specific cohort? I hope that makes sense. I know PIT-tagged salmon can be ID'd to the individual level but wasn't sure how this fit into the temporal aspect of `day` in our dataset.

My follow-up to this is whether we are supposed to measure `survival` as the proportion of smolts:adults or adults:smolts? I could see SAR being interpreted both ways.

**Comment by mjzahn** [comment]
Based on your paper that you reference, I'm guessing the proportion is adults:smolts :)

**Comment by mdscheuerell** [comment]
> This may be obvious for some, but I want to clarify whether the day column in our HW 7 data is in reference to detections of both smolts and adults at BON on the same day?

To clarify :

`smolts` is the number of smolts that were detected at BON on that `day` (May 1-31);

`adults` for a given `day` is the number `smolts` from that `day` that were subsequently detected at BON 1-4 years later (ie, the number of survivors).

> Based on your paper that you reference, I'm guessing the proportion is adults:smolts :)

👍

**Comment by mjzahn** [comment]
Thank you!!
