### ISSUE TITLE
GLM non-integer error (hw #7)

### ISSUE THREAD

**Issue by ameliaduvall** [QERM514/assistance#49]
I am receiving "non-integer" errors when I try to run my glm models. I am using "survival" as my response (adults/smolt) and a Poisson distribution since these are count data. After doing some googling, it looks like the error might be since I'm using a proportion as my response. Does anyone have any insight on where I'm going astray here? Thanks!

**Comment by mdscheuerell** [comment]
Hi @ameliaduvall. There are alternative ways to pass the response info for the binomial to `glm()`. Look back at the elk pellet example from lab [here](https://qerm514.github.io/website/labs/week_07/fitting_glms.html#elk_in_clear_cuts).

**Comment by ameliaduvall** [comment]
Thank you @mdscheuerell. I chose the wrong distribution, classic!
