### ISSUE TITLE
SSTO for glms

### ISSUE THREAD

**Issue by eileenbates** [QERM514/assistance#50]
I'm wondering how we can calculate the SSTO for a model we've run using GLM. For linear mixed models, I know we could use the response variable and the mean value for the response variable to get an SSTO. Now that we are essentially inputting two columns in for our response variable though, I'm a little bit confused as to how to calculate the SSTO (and eventually R^2) in R. This was my attempt:

sse<- sum(residuals(mod1)^2)
survival.ratio<- chinook_data$adults/(chinook_data$smolts-chinook_data$adults)
ssto<- sum((survival.frac-(mean(survival.frac)))^2)
1-(sse/ssto)

This gives me an absurdly large R^2 value (4000 something), which is clearly not wrong. That could be because I've set up the model wrong and therefore have the wrong residuals to begin with, but I'm wondering if part of the problem is this method of calculating SSTO, and what one might do instead.

**Comment by eileenbates** [comment]
**clearly not right

**Comment by mdscheuerell** [comment]
Hi @eileenbates. It turns out that we can't calculate R<sup>2</sup> for a GLM in the same manner we would for regular linear models. Take a look back at [these slides](https://qerm514.github.io/website/lectures/week_07/lec_20_overdispersed_binary_data.html#16) from lec 20.

**Comment by eileenbates** [comment]
Ah yes thanks! Shouldn't have gone back to previous tactics so quickly...
