### ISSUE TITLE
mean survival rate

### ISSUE THREAD

**Issue by hmcmonagle** [QERM514/assistance#51]
Hi all! If we're getting a negative survival rate from the results of our glm, how do we transform that into a real survival rate, i.e. get out of logit space? Perhaps we already covered this and I'm missing it. For question d), I assume we want to provide something more like "mean survival is 1%" as opposed to providing the negative number that the intercept-only model estimated and that the glm() output gives us, since a negative number doesn't make much biological sense as a survival rate.

**Comment by mdscheuerell** [comment]
Good Q, @hmcmonagle. Remember that the coefficients from your model describe the relationship to the linear predictor (eta), not to the response. For logistic regression models, the relationship between eta and p is given by a logit transform, where

logit(p) = log(p / [1-p]) = eta

so you need to find the inverse (ie, the "mean function"). Take a look back at [lab 7](https://qerm514.github.io/website/labs/week_07/fitting_glms.html) to see how we defined the mean function for several different link functions.

**Comment by hmcmonagle** [comment]
Awesome, thanks Mark!

Also, Marie's Issue about SAR (adults/smolts) was really helpful, but I'm wondering if "survival rate", as a percentage, also refers to adults/smolts * 100, or something else (adults/dead smolts, explained below).

As far as I understand from the elk example, we want to put in vectors of presence (adults that survived to come back to BON) and absence (dead smolts that never returned) into the glm() function, where dead smolts = total smolts leaving BON - those that return as adults. 

I can't say I understand a whole lot about the inner computational workings of glm(), though I do see how passing it raw presence/absence data preserves the counts within each day's ratio (as in [lec3](https://qerm514.github.io/website/lectures/week_01/lec_03_data_types.html#22), the ratio 300/900 gives us more confidence than 3/9). So I'm wondering if the intercept glm() spits out, after we transform it, is actually going to give us adults/dead smolts, since that's what I passed it, rather than adults/total smolts, which is how I want to calculate survival rate. I'm guessing glm() was designed cleverly enough to give us the latter, but wanted to make sure.

**Comment by mdscheuerell** [comment]
> I'm wondering if "survival rate", as a percentage, also refers to adults/smolts * 100, or something else (adults/dead smolts, explained below).

We're thinking of survival (ie, "SAR" in Scheuerell et al 2009) as adults/smolts. You could certainly multiply by 100 if you'd like to express that as a precent.

> I'm wondering if the intercept glm() spits out, after we transform it, is actually going to give us adults/dead smolts, since that's what I passed it, rather than adults/total smolts, which is how I want to calculate survival rate.

Yes, `glm()` is smart enough to know that you want an estimate of

successes / (successes + failures)

**Comment by ameliaduvall** [comment]
Thank you @hmcmonagle and @mdscheuerell. I was wondering the same thing.

**Comment by hmcmonagle** [comment]
Ok thanks Mark! I should have had more faith in glm()'s cleverness.
