### ISSUE TITLE
Deviance discrepancy

### ISSUE THREAD

**Issue by greenamy808** [QERM514/assistance#52]
In lecture on Friday, slide 37, you calculated deviance of the full model, but when you calculate the p-value, you only referred to the full model deviance value.
In lab on Friday, you calculated the deviance for full, then deviance for null, then subtracted them before calculating the p-value in the {r model_dev} chunk.
What's the difference here that I'm missing?

**Comment by mdscheuerell** [comment]
Good Q, @greenamy808.

The test on [slide 27](https://qerm514.github.io/website/lectures/week_07/lec_21_modeling_count_data.html#27) from lecture on 5/15 is a goodness-of-fit test for a Poisson model fit to the prawn data.

The test in lab on 5/15 [here](https://qerm514.github.io/website/labs/week_07/fitting_glms.html#inference) is comparing a model with predictors to a model without (ie, only an intercept).
