### ISSUE TITLE
Overlay model fit

### ISSUE THREAD

**Issue by mjzahn** [QERM514/assistance#53]
I've calculated the model-averaged prediction of survival across all four models for part (j) in this week's homework, but I'm stuck on the model-averaged prediction overlay. With the averaged model, we have coefficient estimates for the intercept, day, temp, and the residuals from our linear model of day and temp. For the overlay, I would normally do a loop, inputting values for X from 1-31 for day, but for the overlay in part (j) do we put zeros in for the other parameters?

**Comment by mdscheuerell** [comment]
Here's a suggestion, @mjzahn:

You have values for all of your predictors for each of the 31 days, so you should be able to compute the predicted survival on each day for each of the four models, whether or not `day` appears in a model. If you know the Akaike weight for each model, you can use them to weight each model's prediction for a given day and sum them up for a given day across the four models.

**Comment by mjzahn** [comment]
Thank you! That helps a lot.
