### ISSUE TITLE
LaTeX error

### ISSUE THREAD

**Issue by abigailkeller** [QERM514/assistance#55]
I keep getting this error when I'm knitting to a PDF. The debugging help file that it refers to hasn't really helped me either. Does anyone have any suggestions? 

```
output file: Keller_qerm514_hw_07.knit.md

! Package pdftex.def Error: File `Keller_qerm514_hw_07_files/figure-latex/day\&
temp-1.pdf' not found: using draft setting.

Error: LaTeX failed to compile Keller_qerm514_hw_07.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Keller_qerm514_hw_07.log for more info.
Execution halted
```

**Comment by mdscheuerell** [comment]
Hi @abigailkeller. I'm pretty sure the error you're getting is a result of trying to use an ampersand `&` in your chunk name (ie, `day&temp`), which is a reserved symbol in LaTeX (and elsewhere). This is tripping up Pandoc when it tries to render the file.

Try changing the chunk name to something like `day_and_temp` and see if that works.

**Comment by abigailkeller** [comment]
THANK YOU
