### ISSUE TITLE
determining overdispersion from glm() output

### ISSUE THREAD

**Issue by hmcmonagle** [QERM514/assistance#57]
Hi Mark, 

In [slide 10](https://qerm514.github.io/website/lectures/week_08/lec_22_overdispersed_count_data.html#10) from the Overdispersed Count Data lecture, we learned that we can determine overdispersion by dividing the Deviance / Degrees of Freedom. Another example is slide 20 in the Modeling Count Data lecture. 

A few question about that:

1) I can see from the lecture recording how we determine the deviance from faraway::sumary() output, but where in the is degrees of freedom in that output? How would you calculate df by hand? The only way I could find df so far is to print out the full summary(), but I'm curious how you figure out df during lecture without printing the longer summary output. 

2) What should we call that value that is Deviance / degrees of freedom, the value that we're comparing to 1 to determine overdispersion?

3) Why do we use Deviance, not Null Deviance, for calculating this overdispersion value?

4) Would you mind explaining a little more why this value indicates overdispersion when much greater than 1?
--> Nevermind, I found the explanation of why c-hat > 1 indicates overdispersion [here](https://qerm514.github.io/website/lectures/week_08/lec_22_overdispersed_count_data.pdf)!

Thanks!

**Comment by hmcmonagle** [comment]
This is where I looked for more explanation about interpreting deviance values and determining degrees of freedom, but this part of the lab is cut off mid-sentence in the [version of the lecture that I have](https://qerm514.github.io/website/labs/week_08/fitting_count_models.html#model_fitting).

**Comment by hmcmonagle** [comment]
Also, how does the overdispersion value found using faraway::sumary() output (e.g. in the spot prawns example) differ from c-hat, i.e. the dispersion parameter, [calculated in the lab on fitting count models](https://qerm514.github.io/website/labs/week_08/fitting_count_models.html#overdispersion) in the sea turtle example?

**Comment by mdscheuerell** [comment]
Good morning, @hmcmonagle. Some answers below.

> I can see from the lecture recording how we determine the deviance from faraway::sumary() output, but where in the is degrees of freedom in that output? How would you calculate df by hand? The only way I could find df so far is to print out the full summary(), but I'm curious how you figure out df during lecture without printing the longer summary output.

Here's the output from `faraway::sumary(ted_mod)`
```
> faraway::sumary(ted_mod)

             Estimate Std. Error z value  Pr(>|z|)
(Intercept) -1.496656   0.632031 -2.3680   0.01788
TED         -0.757065   0.176934 -4.2788 1.879e-05
temp         0.073133   0.030238  2.4185   0.01558

n = 197 p = 3
Deviance = 345.29336 Null Deviance = 369.77029 (Difference = 24.47693)
```
The degrees of freedom used to estimate the "dispersion parameter" (ie, `c_hat`) is (*n-k*), where *n* is the sample size (`n = 197`) and *k* is the number of parameters in the model (`p = 3`).

> What should we call that value that is Deviance / degrees of freedom, the value that we're comparing to 1 to determine overdispersion?

We refer to this as the "dispersion parameter", which we've been abbreviating as $\hat{c}$ or `c_hat`.

> Why do we use Deviance, not Null Deviance, for calculating this overdispersion value?

The `Null Deviance` is for a model with only an intercept and no predictors.

> Also, how does the overdispersion value found using faraway::sumary() output (e.g. in the spot prawns example) differ from c-hat, i.e. the dispersion parameter, calculated in the lab on fitting count models in the sea turtle example?

There are 2 different ways to estimate the dispersion parameter:

1) c_hat = D / (n - k)

2) c_hat = X^2 / (n -k)

where X^2 is defined [here](https://qerm514.github.io/website/lectures/week_07/lec_21_modeling_count_data.html#29). With some models method (1) can be less reliable, so we tend to rely more on (2).

> this part of the lab is cut off mid-sentence in the version of the lecture that I have.

Oops! I'll have to fix that.

**Comment by hmcmonagle** [comment]
Hi Mark, 

Gotcha. Regarding my first question, I thought df was just n - k (where k is the number of parameters, aka "p" in the sumary table) but in the lecture below, we learned df was "about 196", so that's where I got tripped up.  Thanks for clarifying that it is indeed 194--I shouldn't have gotten so hung up on that! 

<img width="1231" alt="Screen Shot 2020-05-31 at 12 40 00 PM" src="https://user-images.githubusercontent.com/43573863/83357747-3b829400-a33c-11ea-915d-fd8269fdb1d2.png">

All makes sense now, thanks!

**Comment by mdscheuerell** [comment]
Oops—that was clearly a mistake on my part!

**Comment by mdscheuerell** [comment]
Also, I fixed the mid-sentence in lab 8 and a couple of mistakes on the lecture slides.

**Comment by hmcmonagle** [comment]
Thanks Mark! No problem at all, makes sense now!
