### ISSUE TITLE
Likelihood ratio tests

### ISSUE THREAD

**Issue by ameliaduvall** [QERM514/assistance#58]
I am trying to determine whether there is support for random effects in my models but I am getting an error when I try to use exactRLRT(). I've tried searching online but I can't figure out where I am going astray. If anyone has an idea of what might be going on, please let me know. Thank you!

The error is: 
Error in exactRLRT(bm_plot, bm_plot_yr, bm_yr) : Invalid <m> specified.

Here's the code I am trying to run:
## Load RLRsim package
library(RLRsim)

## Run model with plot RE only
bm_plot <- glmer(Success ~ Type + (1 | Plot), data = SCMU, family = binomial)

## Run model with year RE only
bm_yr <- glmer(Success ~ Type + (1 | Year), data = SCMU, family = binomial)

## Run model with both REs
bm_plot_yr <- glmer(Success ~ Type + (1 | Plot) + (1 | Year), data = SCMU, family = binomial)

## test `Plot` model
exactRLRT(bm_plot,bm_plot_yr, bm_yr)

## test `Year` model
exactRLRT(bm_yr, bm_plot_yr, bm_plot)

**Comment by mdscheuerell** [comment]
The functions in **RLRsim** won't work on GLMMs, but you can still do the test by hand.

```
## Run model with plot RE only
bm_plot <- glmer(Success ~ Type + (1 | Plot), data = SCMU, family = binomial)

## Run model with year RE only
bm_yr <- glmer(Success ~ Type + (1 | Year), data = SCMU, family = binomial)

## Run model with both REs
bm_plot_yr <- glmer(Success ~ Type + (1 | Plot) + (1 | Year), data = SCMU, family = binomial)
```

We can then conduct an LRT to see if the variance of the `Plot` RE is contributing useful info by

```
test_1 <- 2 * (logLik(bm_plot_yr) - logLik(bm_yr))
pchisq(as.numeric(test_1), df = 1, lower.tail = FALSE)
```

and for the contribution of `Year` with

```
test_2 <- 2 * (logLik(bm_plot_yr) - logLik(bm_plot))
pchisq(as.numeric(test_2), df = 1, lower.tail = FALSE)
```

**Comment by ameliaduvall** [comment]
Ah, thank you so much @mdscheuerell! I suspected that might be the case.
