### ISSUE TITLE
couldn't find repos from this page

### ISSUE THREAD

**Issue by hmcmonagle** [QERM514/assistance#6]
<img width="1280" alt="Screen Shot 2020-04-01 at 2 15 14 PM" src="https://user-images.githubusercontent.com/43573863/78172031-5cedff00-7423-11ea-81c7-6fd733f4017b.png">

**Comment by hmcmonagle** [comment]
Got em! I just needed to go to https://github.com/QERM514 (to match the URL of this webpage) instead of github.com/mdscheuerell/QERM514 (as in my screen shot above). Thanks for explaining Mark!

**Comment by mdscheuerell** [comment]
OK, I'm glad we got it figured out.
