### ISSUE TITLE
RStudio integration with GitHub

### ISSUE THREAD

**Issue by divyaOakGrovian** [QERM514/assistance#8]
I installed RStudio on my Windows laptop. But, the IDE does not show an integration with GitHub by default. Is there a configuration setting for it?

**Comment by mdscheuerell** [comment]
We discussed this briefly in lecture on 4/6, but you will need to have **Git** installed before you can select it as a version control option within the **RStudio** preferences.

**Comment by divyaOakGrovian** [comment]
Thanks Mark! Actually, I already had Git installed on my system. Subsequently, I tried to "Enable version control interface for RStudio projects" by providing the path for Git executable, both to 'Global options' and 'Project options' under Tools on the menu. I see the 'Git' tab added to the Project Environment, but not to the Global Environment. I'll dig further after this week's HW. Thanks!

**Comment by divyaOakGrovian** [comment]
Closing the issue now.
